apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sc-geostrategic-karir-lowongan
  namespace: sc-geostrategic
  labels:
    app: sc-geostrategic
    kind: sc-geostrategic-karir-lowongan
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: sc-geostrategic
            kind: sc-geostrategic-karir-lowongan
        spec:
          hostAliases:
            - ip: 10.12.1.101
              hostnames:
                - kafka01.research.ai
            - ip: 10.12.1.102
              hostnames:
                - kafka02.research.ai
            - ip: 10.12.1.103
              hostnames:
                - kafka03.research.ai
          volumes:
            - name: config
              configMap:
                  name: config-karir-lowongan
          containers:
          - name: sc-geostrategic-karir-lowongan
            image: 192.168.202.50/crawler/geostrategic/karir_lowongan:1.1
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py", "--headless", "--kafka"]
          restartPolicy: Never